### PR TITLE
Re-use PanLogger instances if the parameters haven't changed.

### LINKED ISSUE #190: get_root_logger creates a new logger on each call
Should return the same PanLogger instance if the params are the same. I have a fix in progress.

### PR DESCRIPTION
**Pull request by jamessynge**
Fixes #190.

### CODE REVIEW

**Comment by jamessynge** [comment]
It appears the build failed due to a network issue. Closing and reopening PR to trigger build again.

**Comment by wtgee** [comment]
>It appears the build failed due to a network issue. Closing and reopening PR to trigger build again.

FYI, there is a Restart Build button on travis. Let me know if you don't have access to it.

**Comment by jamessynge** [comment]
As long as importing works correctly, all the imports of pocs.utils.logger will reference the same one module instance, so they'll share the same global (module scope) variable `all_loggers`. And thus a single PanLogger is created.

**Comment by wtgee** [comment]
Let's remove the global `_logger` and just use this setup. It is essentially the same thing.

**Comment by jamessynge** [comment]
PTAL

**Pull request merged**
