### PR TITLE
issue #343

### PR DESCRIPTION
**Pull request by kmeagle1515**
This is a PR #802 on how to upload a arduino code on linux if error has occured.
Those commands solve the issue .
However this code won't be included in the Readme,it will be included in the instructions guide which is currently in progress.
Here is the issue #343

### CODE REVIEW

**Comment by AnthonyHorton** [comment]
Content looks good. I'll leave it to @wtgee to decide whether this belongs in `README.md` or whether it should be in the Wiki instead (I suspect the latter).

A few general points:

* PR titles should be a short description of what the changes do, not just the number of a related Issue.
* Related Issues should be referenced by number in the description (not just the title), where GitHub will automatically linkify them, e.g. "this will fix Issue #343".
* You should be using feature branches in your fork of the POCS repo and making your Pull Requests from them, not your `develop` branch. See the suggested workflow described in the wiki: https://github.com/panoptes/POCS/wiki/Feature-Development-Process
* When you'd like a review request one using the Reviewers settings on the right, that triggers notifications & filters so that it's easier for people to notice that a review is needed. You can use the 'POCS Developers' option at the bottom of the list when you don't have an individual reviewer in mind.

**Comment by kmeagle1515** [comment]
Thanks for the feedback sir!

**Comment by wtgee** [comment]
Hi @kmeagle1515, thanks for the PR! I think the most appropriate place for this is actually in our instruction guide, which we are redoing right now and will be in the [Instructions](https://projectpanoptes.org/instructions/) area of our main website. I'll move some of this text over to that document, which is a google doc that will soon be shared via that Instructions page.

However, I think this would also be helpful to have on the forum. Can you post in the [Building](https://forum.projectpanoptes.org/c/building) section with a title like "Permission problems while connecting to arduino"? The text you have in this PR is good for that. 

Once posted there can you add the link back here and then we'll close the PR. Thanks!

**Comment by kmeagle1515** [comment]
Sure,why not.

**Comment by kmeagle1515** [comment]
@wtgee i have done that.

**Comment by wtgee** [comment]
@kmeagle1515 can you put the actual text from the README in this PR into the question on the forum rather than just linking to here? I want to close this issue without merging into the README but want the information directly available in the forum.

I'll also get it into the documentation and be sure to get you credit there as well. Thanks!

**Comment by kmeagle1515** [comment]
@wtgee done!

**Comment by wtgee** [comment]
Awesome, thanks @kmeagle1515! I changed one thing to fix the encoding that came through incorrectly but other than that looks good. This wording will go into the docs as well but doesn't necessarily have a place in the README, so I am going to close the issue. Thanks again!

**Pull request closed without merging**
