### PR TITLE
Issue #631 exp_time vs exptime consistency

### PR DESCRIPTION
**Pull request by ImmortalRabbit**
I have replaced variables exp_time, exptime by exposure and EXPTIME by EXPOSURE.

### CODE REVIEW

**Comment by wtgee** [comment]
Thanks @ImmortalRabbit! Glad you could jump right in.

@AnthonyHorton you had made the recommendation of `EXPOSURE` (in #631), see any issues with us switching it at this point. I do feel like `EXPTIME` is more common as a FITS header.  

@joshwalawender might also have an opinion.

I'm happy to do the actual code review.

**Comment by AnthonyHorton** [comment]
Yes, I'm inclined to stick with `EXPTIME` for the FITS headers. It's far more commonly used than `EXPOSURE` in that context, and I'm loathe to change FITS header keywords unless we really have to. Want to avoid breaking data reduction/analysis code that expects a particular set of keywords!

`exposure` would be fine everywhere else, but then that means we've still got a naming inconsistency, just a different one.

**Comment by wtgee** [comment]
I would tend to agree, especially regarding the `EXPTIME` as a FITS keyword. The variable names are not as important but I think the `exptime` consistency would be nice.

@ImmortalRabbit sorry for the lack of clarity in #631. Can you change this to use `exptime` and `EXPTIME` accordingly?  Thanks!

Also, are you approaching this from GSoC?

**Comment by ImmortalRabbit** [comment]
> I would tend to agree, especially regarding the `EXPTIME` as a FITS keyword. The variable names are not as important but I think the `exptime` consistency would be nice.
> 
> @ImmortalRabbit sorry for the lack of clarity in #631. Can you change this to use `exptime` and `EXPTIME` accordingly? Thanks!
> 
> Also, are you approaching this from GSoC?

Yes, I will change.
Yes, I am approaching this from GSoC. Sorry, for my messy pull request, just starting to learn how to contribute.

**Pull request closed without merging**
