### PR TITLE
Consolidate repos

### LINKED ISSUE #98: Consolidate POCS, PEAS, and PACE
We want to merge the three separate repos so there is less confusion for new users as to what is going on.

### PR DESCRIPTION
**Pull request by wtgee**
Closes #98 

This pulls in the histories for both PACE and PEAS

### CODE REVIEW

**Comment by jamessynge** [comment]
Can we hold off on merging this into develop until we've got PAN006 running automatically?

**Comment by wtgee** [comment]
> Can we hold off on merging this into develop until we've got PAN006 running automatically?

I'm thinking about merging it into a separate branch but I guess not totally necessary. My other thought is that we should get `develop` to a decent state soon and merge it into `master` and switch PAN006 to that. Then we can do "hotfixes" on `master` and move those back to develop. Thoughts?

**Comment by jamessynge** [comment]
I think that starting a new branch for the merge makes sense. It will probably take a while to get things in order, so a separate branch would be best.

And I think think the idea of updating master periodically, along with using tags, also makes sense. That way we can tell builders to use a specific tag, or ask them to use master to test a hotfix.

**Comment by wtgee** [comment]
Replaced by #124 which merges into new branch.

**Pull request closed without merging**
