### PR TITLE
Horizon ranges

### PR DESCRIPTION
**Pull request by danjampro**
Add support for a state to specify a "bright horizon", meaning that `pocs.is_safe()=True` only when the Sun is between `horizon` and `horizon_bright`. Useful for e.g. taking twilight flat fields before it gets too dark.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by wtgee** [comment]
I'm not terribly keen on adding the `horizon_bright` to the `is_safe` and related methods, although I'm not sure why. Doesn't seem very clean to me.

How would the bright horizon differ from the flat, focus, and observe horizons?  I realize we talked about this some in the slack channel but it's not clear to me that this does immediately solve the problem.

If we really need to finely distinguish between horizon levels I guess I would rather build in more thorough support so that a `pocs` instance (really the `pocs.observatory.observer`) can directly figure out horizon levels rather than have some side state logic.  

Thoughts? @AnthonyHorton @danjampro

**Comment by danjampro** [comment]
> I'm not terribly keen on adding the `horizon_bright` to the `is_safe` and related methods, although I'm not sure why. Doesn't seem very clean to me.
> 
> How would the bright horizon differ from the flat, focus, and observe horizons? I realize we talked about this some in the slack channel but it's not clear to me that this does immediately solve the problem.
> 
> If we really need to finely distinguish between horizon levels I guess I would rather build in more thorough support so that a `pocs` instance (really the `pocs.observatory.observer`) can directly figure out horizon levels rather than have some side state logic.
> 
> Thoughts? @AnthonyHorton @danjampro

Thanks for looking at this. We are basically just trying to get the state machine to wait until it is bright enough to take flats. This is particularly important when entering the morning twilight flats state after finishing observing. So in this case, we could have something like `bright_horizon='focus'`.

I'm not sure what you mean by "clean" in this case. I would say it is, because it leaves current use cases unaffected while implementing (I think) our desired behaviour, with not too much additional code - most of it just mirrors existing code for the normal horizon. But I'm interested to hear your suggestions!

**Comment by AnthonyHorton** [comment]
@wtgee The re-use of the `focus` horizon as the `bright_horizon` for flat fielding is possibly obscuring the intent here.

The rationale behind these changes is that the existing `is_dark` and `is_safe` checks, and the corresponding wait until dark mechanism in the state machine, only work with a single Sun altitude limit (horizon), a maximum Sun altitude. For twilight flats we need the Sun altitude to be within a specific range, i.e. a single state needs to have both a minimum and maximum Sun altitude associated with it. This is especially important for morning twilight flats because without this the state machine will transition to the twilight flats state as soon as it gets too bright for observing, when it is still far too dark for flats. We could implement a 'wait until morning twilight' function in  `huntsman-pocs` but that would involve duplicating some of the existing functionality in POCS, so it seems cleaner to add support for a minimum Sun altitude to POCS instead.

**Comment by wtgee** [comment]
> @wtgee The re-use of the `focus` horizon as the `bright_horizon` for flat fielding is possibly obscuring the intent here.
> 
> The rationale behind these changes is that the existing `is_dark` and `is_safe` checks, and the corresponding wait until dark mechanism in the state machine, only work with a single Sun altitude limit (horizon), a maximum Sun altitude. For twilight flats we need the Sun altitude to be within a specific range, i.e. a single state needs to have both a minimum and maximum Sun altitude associated with it. This is especially important for morning twilight flats because without this the state machine will transition to the twilight flats state as soon as it gets too bright for observing, when it is still far too dark for flats. We could implement a 'wait until morning twilight' function in `huntsman-pocs` but that would involve duplicating some of the existing functionality in POCS, so it seems cleaner to add support for a minimum Sun altitude to POCS instead.

It's not the rationale that is confusing me at all or that I don't like, it's the implementation.

Our horizons already have "borders" so I was thinking we could just use the knowledge of what horizon we are in to define those borders. I guess I was wondering if those bright limits need to take place between established horizon limits or not.  That is, is `horizon_bright` always going to be equal to the `focus` altitude? Even if we need an in-between it seems like we could add another horizon level, then just tag the state with the existing mechanism to require certain horizons.

In particular it is adding the `bright_horizon` as a parameter to `is_safe` that seems off to me for some reason.

I don't have a ton of better suggestions however.

**Comment by danjampro** [comment]
> > @wtgee The re-use of the `focus` horizon as the `bright_horizon` for flat fielding is possibly obscuring the intent here.
> > The rationale behind these changes is that the existing `is_dark` and `is_safe` checks, and the corresponding wait until dark mechanism in the state machine, only work with a single Sun altitude limit (horizon), a maximum Sun altitude. For twilight flats we need the Sun altitude to be within a specific range, i.e. a single state needs to have both a minimum and maximum Sun altitude associated with it. This is especially important for morning twilight flats because without this the state machine will transition to the twilight flats state as soon as it gets too bright for observing, when it is still far too dark for flats. We could implement a 'wait until morning twilight' function in `huntsman-pocs` but that would involve duplicating some of the existing functionality in POCS, so it seems cleaner to add support for a minimum Sun altitude to POCS instead.
> 
> It's not the rationale that is confusing me at all or that I don't like, it's the implementation.
> 
> Our horizons already have "borders" so I was thinking we could just use the knowledge of what horizon we are in to define those borders. I guess I was wondering if those bright limits need to take place between established horizon limits or not. That is, is `horizon_bright` always going to be equal to the `focus` altitude? Even if we need an in-between it seems like we could add another horizon level, then just tag the state with the existing mechanism to require certain horizons.
> 
> In particular it is adding the `bright_horizon` as a parameter to `is_safe` that seems off to me for some reason.
> 
> I don't have a ton of better suggestions however.

I'm not sure that we will end up using `horizon='focus'` as maybe even that is too dark for the flats, we will have to see during commissioning.  

If you don't like the extra horizon being passed into `is_safe` via `wait_until_safe` (as far as I can see, the simplest solution), then there will have to be an additional call to some sort of wait function somewhere else in the code, which is the sort of thing we were trying to avoid doing in huntsman-pocs. I don't really get what "tagging" the states means though, so maybe there is a better solution - if you can suggest one? Maybe a function like `wait_for_state_conditions` can replace the call to `wait_until_safe` or something...

**Comment by AnthonyHorton** [comment]
> Our horizons already have "borders" so I was thinking we could just use the knowledge of what horizon we are in to define those borders. I guess I was wondering if those bright limits need to take place between established horizon limits or not. That is, is `horizon_bright` always going to be equal to the `focus` altitude? Even if we need an in-between it seems like we could add another horizon level, then just tag the state with the existing mechanism to require certain horizons.

No, in general the minimum Sun altitude limit for twilight flats will not be the same as the maximum Sun altitude limit for focusing. Even if they do have the same numerical value for now they should certainly not be sharing the same name because they have distinct purposes Re-using the `focus` horizon instead of adding a new one was a mistake here, & in general the naming could be improved to make things clearer.

I guess I missed the horizons' "borders".  How do they work?

A note about relevant future plans. The twilight flats autoexposure algorithm is great but I think it's clear that when using twilight flats for wide field imaging systems you really want to be using consistent Sun altitudes for best results, especially between evening and morning twilight flats so that you can cancel sky gradients. Once we've actually got a bit more twilight flat data I think we can pretty quickly settle on a very narrow range of Sun altitudes that work best. These will be different for each filter, of course. Most of the implementation for all of that will naturally go into the `twilight_flat_fielding` state, but having a good 'safely wait until the sun altitude is between these two limits` function is going to be very useful.

**Comment by wtgee** [comment]
@danjampro is this PR still relevant?

**Comment by wtgee** [comment]
Closing in favor of https://github.com/AstroHuntsman/huntsman-pocs/pull/183

**Pull request closed without merging**
