### PR TITLE
Use panoptes installation of solve-field (astrometry).

### PR DESCRIPTION
**Pull request by jamessynge**

### CODE REVIEW

**Comment by jamessynge** [comment]
Added code to issue an error if missing solve-field.

**Comment by wtgee** [comment]
Actually, with this in place we should probably capture and handle as well.

https://github.com/panoptes/POCS/blob/develop/pocs/camera/canon_gphoto2.py#L178

**Comment by jamessynge** [comment]
Sorry, I don't understand the comment about "capture and handle".

**Comment by wtgee** [comment]
> Sorry, I don't understand the comment about "capture and handle".

Probably because I linked to wrong place. See #116

**Pull request merged**
